bin/testflinger-run: TF no longer requires VPN
Also change the URL to one that doesn't require OIDC authentication.

Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/bin/testflinger-run b/bin/testflinger-run
--- a/bin/testflinger-run
+++ b/bin/testflinger-run
@@ -79,8 +79,8 @@ EOF
 
 setup_testflinger() {
     # Test connectivity
-    if ! wget --method HEAD -qO /dev/null https://testflinger.canonical.com/agents; then
-        echo "Failed to connect to testflinger.canonical.com, make sure you are connected to the VPN" >&2
+    if ! wget --method HEAD -qO /dev/null https://testflinger.canonical.com/; then
+        echo "Failed to connect to testflinger.canonical.com" >&2
         exit 1
     fi
 
