github: fix indent of commits job
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/.github/workflows/commits.yml b/.github/workflows/commits.yml
--- a/.github/workflows/commits.yml
+++ b/.github/workflows/commits.yml
@@ -14,23 +14,23 @@ jobs:
     name: Branch target and CLA
     runs-on: ubuntu-latest
     steps:
-    - name: Check branch target
-      env:
-        TARGET: ${{ github.event.pull_request.base.ref }}
-        TITLE: ${{ github.event.pull_request.title }}
-      if: ${{ github.actor != 'dependabot[bot]' }}
-      run: |
-        set -eux
-        TARGET_FROM_PR_TITLE="$(echo "${TITLE}" | sed -n 's/.*(\(stable-[0-9]\+\.[0-9]\+\))$/\1/p')"
-        if [ -z "${TARGET_FROM_PR_TITLE}" ]; then
-          TARGET_FROM_PR_TITLE="main"
-        else
-          echo "Branch target overridden from PR title"
-        fi
-        [ "${TARGET}" = "${TARGET_FROM_PR_TITLE}" ] && exit 0
+      - name: Check branch target
+        env:
+          TARGET: ${{ github.event.pull_request.base.ref }}
+          TITLE: ${{ github.event.pull_request.title }}
+        if: ${{ github.actor != 'dependabot[bot]' }}
+        run: |
+          set -eux
+          TARGET_FROM_PR_TITLE="$(echo "${TITLE}" | sed -n 's/.*(\(stable-[0-9]\+\.[0-9]\+\))$/\1/p')"
+          if [ -z "${TARGET_FROM_PR_TITLE}" ]; then
+            TARGET_FROM_PR_TITLE="main"
+          else
+            echo "Branch target overridden from PR title"
+          fi
+          [ "${TARGET}" = "${TARGET_FROM_PR_TITLE}" ] && exit 0
 
-        echo "Invalid branch target: ${TARGET} != ${TARGET_FROM_PR_TITLE}"
-        exit 1
+          echo "Invalid branch target: ${TARGET} != ${TARGET_FROM_PR_TITLE}"
+          exit 1
 
-    - name: Check if CLA signed
-      uses: canonical/has-signed-canonical-cla@046337b42822b7868ad62970988929c79f9c1d40  # 1.2.3
+      - name: Check if CLA signed
+        uses: canonical/has-signed-canonical-cla@046337b42822b7868ad62970988929c79f9c1d40  # 1.2.3
